[package]
name = "rudy-types"
version = "0.4.3"
edition = "2024"
description = "Type layouts of common Rust types for Rudy"
license = "MIT"
rust-version.workspace = true

[dependencies]
itertools.workspace = true
salsa.workspace = true
