[package]
name = "rudy-types"
version = "0.1.0"
edition = "2024"
description = "Type layouts of common Rust types for Rudy"
license = "MIT"

[dependencies]
itertools.workspace = true
salsa.workspace = true
