[package]
name = "rust_debuginfo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
chalk-ir = "0.100.0"
gimli = { version = "0.31.1", default-features = false, features = [
    "std",
    "read",
    "endian-reader",
] }
itertools = "0.14.0"
memmap2 = "0.9.5"
object = { git = "https://github.com/gimli-rs/object", rev = "a74579249e21ab8fcd3a86be588de336f18297cb" }
rustc-demangle = "0.1"
salsa = "0.19.0"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "time"] }


[dev-dependencies]
insta = "1.42.2"
rstest = "0.25"
rstest_reuse = { version = "0.7" }
