[workspace]
members = ["rdi-lldb", "rust-debuginfo"]
resolver = "3"

[workspace.dependencies]
rust-debuginfo = { path = "rust-debuginfo" }


[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
