[package]
name = "test-utils"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow.workspace = true
insta.workspace = true
rstest.workspace = true
rstest_reuse.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
