name: Rust CI checks
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run formatting
        run: cargo fmt --all --check
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings

  # TODO: need to figure out a reasonable way to run thes
  # in CI given that so much is platform-specific
  # test:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Rust stable toolchain
  #       uses: dtolnay/rust-toolchain@stable
  #     - name: Run tests
  #       run: |
  #         cargo test --all-targets
  #         cargo test --doc
