name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  # Run static tests (can run on any platform with checked-in artifacts)
  static-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Download test artifacts
      run: |
        echo "📦 Downloading latest test artifacts..."
        cargo xtask download-artifacts
    
    - name: Run unit tests
      run: cargo test --lib
    
    - name: Run doc tests
      run: cargo test --doc

    - name: Run static tests
      run: cargo test -p rudy-db --test static_tests


  # Run dynamic tests on each platform
  dynamic-tests:
    strategy:
      matrix:
        include:
          # TODO: make these work
          # - os: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Download test artifacts
      run: |
        echo "📦 Downloading latest test artifacts..."
        cargo xtask download-artifacts
    
    - name: Run dynamic tests
      run: cargo test -p rudy-db --test dynamic_tests --target ${{ matrix.target }}
    
