name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  # Run tests on each platform
  tests:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - uses: taiki-e/install-action@v2
      with:
        tool: nextest
        
    - name: Download test artifacts
      run: |
        echo "📦 Downloading latest test artifacts..."
        cargo xtask download-artifacts
    
    # Run all tests
    # NOTE: see `.config/nextest.toml` for the default filter
    - name: Run tests
      run: |
        echo "🚀 Running tests for target: ${{ matrix.target }}"
        cargo nextest run --profile ci

